# -*- coding: utf-8 -*-
"""Mini_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13mO6f2UZL3Rj5wkvRbNWB7wYj_vtKPJ_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import  RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix

titanic_raw = pd.read_csv('titanic.csv')
titanic_raw.keys()

titanic = titanic_raw.drop(columns= ['PassengerId', 'Name', 'Ticket', 'Cabin'])
titanic.head()

titanic['FamilySize'] = titanic['SibSp'] + titanic['Parch'] + 1
titanic['FamilySize'].value_counts()

titanic['isAlone'] = (titanic['FamilySize'] == 1).astype(int)
titanic['isAlone'].value_counts()

titanic['MotherChild'] = ((titanic['Sex'] == 'female') & (titanic['Parch'] > 0)).astype(int)
titanic['MotherChild'].value_counts()

sns.barplot(x='FamilySize', y='Survived', data=titanic)

sns.barplot(x='isAlone', y='Survived', data=titanic)

sns.barplot(x='MotherChild', y='Survived', data=titanic)

sns.barplot(x='Sex', y='Survived', data=titanic)

titanic_df = pd.DataFrame(titanic)
titanic_df.isna().sum()

titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].median())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna(titanic_df['Embarked'].mode()[0])
titanic_df.isna().sum()

input = titanic_df.drop(columns= ['Survived'])
target = titanic_df['Survived']

process = ColumnTransformer(
    transformers=[
        ('Encoder', OneHotEncoder(drop='first', sparse_output=False), ['Sex', 'Embarked'])
    ],
    remainder='passthrough',
    # force_int_remainder_cols=False
)

pl = Pipeline([
    ('processing', process),
    ('model', RandomForestClassifier(n_estimators=200))
])

X_train, X_test, Y_train, Y_test = train_test_split(input, target, test_size=0.2, random_state=42)

pl.fit(X_train, Y_train)

pl.score(X_test, Y_test)

Y_pred = pl.predict(X_test)

cm = confusion_matrix(Y_test, Y_pred)

plt.figure(figsize= (8, 5))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=['Died','Survived'],
            yticklabels=['Died','Survived'])

plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')

feature_names = pl.named_steps['processing'].get_feature_names_out()
model = pl.named_steps['model']

for name, score in zip(feature_names, model.feature_importances_):
    print(name, score)

test_data = pd.DataFrame({
    'Pclass':[3,1,3],
    'Sex':['male','female','male'],
    'Age':[22,35,30],
    'SibSp':[1,0,0],
    'Parch':[0,0,0],
    'Fare':[7.25,80,8],
    'Embarked':['S','C','Q'],
    'FamilySize':[2,1,1],
    'isAlone': [0, 1, 1],
    'MotherChild': [1, 0, 1]
})

pl.predict(test_data)

pl.predict_proba(test_data)

pickle.dump(pl, open('titanic_model2', 'wb'))